const actionTypes = {
  FETCHING_TODOS: 'FETCHING_TODOS',
  FETCHING_TODOS_SUCCESS: 'FETCHING_TODOS_SUCCESS',
  DELETING_TODO: 'DELETING_TODO',
  DELETING_TODO_SUCCESS: 'DELETING_TODO_SUCCESS',
  ADDING_TODO: 'ADDING_TODO',
  ADDING_TODO_SUCCESS: 'ADDING_TODO_SUCCESS',
  SWITCHING_TODO: 'SWITCHING_TODO',
  SWITCHING_TODO_SUCCESS: 'SWITCHING_TODO_SUCCESS'
}

export default actionTypes;